shopt -s expand_aliases  
# Aliases
alias st='tmux source-file ~/.tmux.conf'
alias sqlite='/usr/local/bin/sqlite3'

# bash
alias sb='source ~/.bashrc'
alias eb='vim ~/.bash/bash_main'
alias ee='vim ~/.bash/bash_environment'
alias ea='vim ~/.bash/bash_aliases'
alias es='vim ~/.bash/bash_secrets'
alias ef='vim ~/.bash/bash_functions'
alias se='source ~/.bash/bash_environment'
alias sa='source ~/.bash/bash_aliases'
alias ss='source ~/.bash/bash_secrets'
alias sf='source ~/.bash/bash_functions'

alias ev='vim ~/.vimrc'
alias ek='vim ~/.config/kak/kakrc'
alias et='vim ~/.tmux.conf'
alias gl='git status'
alias gvim='vim.gtk'
alias gp='git push'
alias git=hub
alias scalabootstrap='sbt new sbt/scala-seed.g8'
alias blogdate='date +"%Y-%m-%d"'
alias grabit='tmux attach-session -d'
alias takeover='tmux detach -a'
alias jserve='bundle exec jekyll serve'
alias makehash='cat /dev/urandom | tr -dc "a-zA-Z0-9" | fold -w 16 | head -n 1'
alias showrecipients=showGPGRecipients
alias clearhistory='history -c && history -w'
alias mitscheme='rlwrap -r -c $HOME/opt/mit-scheme/src/microcode/scheme  --band $HOME/opt/mit-scheme/src/lib/runtime.com'
alias javarepl='java -jar $HOME/bin/javarepl-428.jar'
alias qrepl='rlwrap q'
# `clipcopy' copies and `clippaste' pastes'
alias clipboard='xclip -sel clip'
alias xclipcopy='xclip -selection clipboard'
alias xclippaste='xclip -selection clipboard -o'
# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
